### ISSUE TITLE
老出现从http://ajax.googleapis.com收取数据

### ISSUE THREAD

**Issue by KunBetter** [heroicyang/hexo-theme-modernist#13]
网页打开很慢,浏览器底部总出现"http://ajax.googleapis.com收取数据"。我不太懂前端，这个如何改进

**Comment by someus** [comment]
![image 1](https://cloud.githubusercontent.com/assets/4159935/5932052/75d4d738-a6e1-11e4-8ac3-4036524fd00c.png)
